# Generated by Django 2.2 on 2019-05-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_shopuserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='tagline',
            new_name='tags',
        ),
    ]
