# Generated by Django 2.2 on 2019-05-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190502_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'МУЖСКОЙ'), ('W', 'ЖЕНСКИЙ')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
