# Generated by Django 2.2 on 2019-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20190506_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='lang',
            field=models.CharField(blank=True, choices=[('0', 'РУССКИЙ'), ('1', 'УКРАИНСКИЙ'), ('2', 'БЕЛОРУССКИЙ'), ('3', 'АНГЛИЙСКИЙ'), ('4', 'ИСПАНСКИЙ'), ('5', 'ФИНСКИЙ'), ('6', 'НЕМЕЦКИЙ'), ('7', 'ИТАЛЬЯРНСКИЙ')], max_length=64, verbose_name='язык'),
        ),
    ]
