# Generated by Django 2.2 on 2019-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20190506_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='lang',
            field=models.CharField(blank=True, choices=[('0', 'РУССКИЙ'), ('3', 'АНГЛИЙСКИЙ')], max_length=1, verbose_name='язык'),
        ),
    ]
