# Generated by Django 2.2 on 2019-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20190506_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='lang',
            field=models.CharField(choices=[('0', 'РУССКИЙ'), ('3', 'АНГЛИЙСКИЙ')], max_length=2, null=True, verbose_name='язык'),
        ),
    ]
