# Generated by Django 2.2 on 2019-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_auto_20190506_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='link_social',
            field=models.URLField(blank=True, max_length=512, verbose_name='ссылка на соцсеть'),
        ),
    ]
