# Generated by Django 2.2 on 2019-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_shopuserprofile_link_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='photo_vk',
            field=models.URLField(blank=True, max_length=512, verbose_name='ссылка на фото ВК'),
        ),
    ]
